//
//  UTTypeIconSource.swift
//  Iconic
//
//  Created by Jeremy Sachs on 1/24/24.
//  Copyright © 2024 Rezmason.net. All rights reserved.
//

import Cocoa
import UniformTypeIdentifiers

@available(macOS 11, *)
class UTTypeIconSource: IconSource {

  private let storage: IconStorage<UTType>

  init() {
    storage = IconStorage(with: { return Icon(image: NSWorkspace.shared.icon(for: $0)) })
    Task.detached { await self.storage.add(contentsOf: utTypes) }
  }

  func icon() async -> Icon? {
    return await storage.icon()
  }
}

@available(macOS 11, *)
private let utTypes: [UTType] = [
  .item,
  .content,
  .compositeContent,
  .diskImage,
  .data,
  .directory,
  .resolvable,
  .symbolicLink,
  .executable,
  .mountPoint,
  .aliasFile,
  .urlBookmarkData,
  .url,
  .fileURL,
  .text,
  .plainText,
  .utf8PlainText,
  .utf16ExternalPlainText,
  .utf16PlainText,
  .delimitedText,
  .commaSeparatedText,
  .tabSeparatedText,
  .utf8TabSeparatedText,
  .rtf,
  .html,
  .xml,
  .yaml,
  .sourceCode,
  .assemblyLanguageSource,
  .cSource,
  .objectiveCSource,
  .swiftSource,
  .cPlusPlusSource,
  .objectiveCPlusPlusSource,
  .cHeader,
  .cPlusPlusHeader,
  .script,
  .appleScript,
  .osaScript,
  .osaScriptBundle,
  .javaScript,
  .shellScript,
  .perlScript,
  .pythonScript,
  .rubyScript,
  .phpScript,
  //  .makefile,
  .json,
  .propertyList,
  .xmlPropertyList,
  .binaryPropertyList,
  .pdf,
  .rtfd,
  .flatRTFD,
  .webArchive,
  .image,
  .jpeg,
  .tiff,
  .gif,
  .png,
  .icns,
  .bmp,
  .ico,
  .rawImage,
  .svg,
  .livePhoto,
  .heif,
  .heic,
  .webP,
  .threeDContent,
  .usd,
  .usdz,
  .realityFile,
  .sceneKitScene,
  .arReferenceObject,
  .audiovisualContent,
  .movie,
  .video,
  .audio,
  .quickTimeMovie,
  .mpeg,
  .mpeg2Video,
  .mpeg2TransportStream,
  .mp3,
  .mpeg4Movie,
  .mpeg4Audio,
  .appleProtectedMPEG4Audio,
  .appleProtectedMPEG4Video,
  .avi,
  .aiff,
  .wav,
  .midi,
  .playlist,
  .m3uPlaylist,
  .folder,
  .volume,
  .package,
  .bundle,
  .pluginBundle,
  .spotlightImporter,
  .quickLookGenerator,
  .xpcService,
  .framework,
  .application,
  .applicationBundle,
  .applicationExtension,
  .unixExecutable,
  .exe,
  .systemPreferencesPane,
  .archive,
  .gzip,
  .bz2,
  .zip,
  .appleArchive,
  .spreadsheet,
  .presentation,
  .database,
  .message,
  .contact,
  .vCard,
  .toDoItem,
  .calendarEvent,
  .emailMessage,
  .internetLocation,
  .internetShortcut,
  .font,
  .bookmark,
  .pkcs12,
  .x509Certificate,
  .epub,
  .log,
]
